baseurl = "/"
languageCode = "en-us"
title = "TidyTuesday @ CorrelAid"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Blog"
    url = "/"
    

[Author]
  name = "CorrelAid"
  email = "info@correlaid.org"
  github = "CorrelAid"
  twitter = "CorrelAid"
  website = "correlaid.org"

  
[Params]
  homeTitle = "TidyTuesday @ CorrelAid" # Set a different text for the header on the home page
  subtitle = ""
  logo = "/img/correlaid_logo.png" # Expecting square dimensions
  favicon = ""
  dateFormat = "2006/01/02"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = false


